---
# Source: https://github.com/netdata/netdata/blob/master/.github/workflows/docs.yml 
name: Docs
on:
  push:
    branches:
      - gh-pages
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
env:
  DO_NOT_TRACK: 1
jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          #check-modified-files-only: 'yes'
